# Generated by Django 4.1.7 on 2024-10-16 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='featured_video',
            field=models.ImageField(upload_to='', verbose_name='featured_video'),
        ),
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(upload_to='', verbose_name='thumbnail'),
        ),
    ]
