# Generated by Django 4.1.7 on 2024-10-16 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_course_featured_video_alter_course_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='lesson_video',
            field=models.ImageField(null=True, upload_to='static/img'),
        ),
    ]
